In [36]:
import numpy as np

In [70]:
D=np.zeros((4,4),dtype=int);np.fill_diagonal(D, 1)
X=np.zeros_like(D); X[:] = np.arange(1, 5).reshape(-1, 1)
print(f'D={D}\n');print(f'X={X}\n')

Nx=5
output = np.zeros((Nx))

np.add.at(output,(X),D)
print(f'output={output}')

D=[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

X=[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]

output=[0. 1. 1. 1. 1.]


In [71]:
D=np.zeros((4,4),dtype=int);np.fill_diagonal(D, 1);
X=np.zeros_like(D); X[:] = np.arange(1, 5).reshape(-1, 1)
Y=np.zeros_like(D); Y[:] = np.arange(1, 5).reshape(-1, 1)
print(f'D={D}\n');print(f'X={X}\n')

Ny=5;Nx=5
output = np.zeros((Ny, Nx))

np.add.at(output,(Y,X),D)
print(f'output={output}')

D=[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

X=[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]

output=[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [72]:
D=np.zeros((4,4),dtype=int);np.fill_diagonal(D, 1);
X=np.zeros_like(D); X[:] = np.arange(1, 5).reshape(-1, 1)
Y=np.zeros_like(D); Y[:] = np.arange(1, 5).reshape(-1, 1)
Z=np.zeros_like(D); Z[:] = np.arange(1, 5).reshape(-1, 1)
print(f'D={D}\n');print(f'X={X}\n')

Nz=5; Ny=5;Nx=5
output = np.zeros((Nz, Ny, Nx))

np.add.at(output,(Z,Y,X),D)
print(f'output={output}')

D=[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

X=[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]

output=[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1.]]]
